---
- hosts: all
  tasks:
    - name: Install wget
      yum: name=wget state=present
    - name: Change to aliyun_repo
      shell: |
        wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
        wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo
        yum clean all && yum makecache
